/*
 * Copyright (C) 2008 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.lewa.launcher;

import com.lewa.launcher.DragController.DragListener;

import android.content.Context;
import android.graphics.Color;
import android.graphics.Rect;
import android.graphics.drawable.ColorDrawable;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.AbsListView;
import android.widget.BaseAdapter;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.AdapterView.OnItemLongClickListener;
import android.widget.RelativeLayout;

/**
 * Represents a set of icons chosen by the user or generated by the system.
 */
public class Folder extends RelativeLayout implements DragSource, OnItemLongClickListener,
        OnItemClickListener, OnClickListener, View.OnLongClickListener, DragListener {

    protected AbsListView mContent;
    protected DragController mDragger;
    
    protected Launcher mLauncher;

    protected Button mCloseButton;
    
    protected FolderInfo mInfo;
    
    /**
     * Which item is being dragged
     */
    protected ApplicationInfo mDragItem;
    /**
     * ADW:Theme vars
     */
    private boolean mIsOnLongClick = false;

    /**
     * Used to inflate the Workspace from XML.
     *
     * @param context The application's context.
     * @param attrs The attribtues set containing the Workspace's customization values.
     */
    public Folder(Context context, AttributeSet attrs) {
        super(context, attrs);
        setAlwaysDrawnWithCacheEnabled(false);
    }

    @Override
    protected void onFinishInflate() {
        super.onFinishInflate();

        mContent = (AbsListView) findViewById(R.id.folder_content);
        mContent.setSelector(new ColorDrawable(Color.TRANSPARENT));
        mContent.setOnItemClickListener(this);
        mContent.setOnItemLongClickListener(this);
        
        mCloseButton = (Button) findViewById(R.id.folder_close);
        mCloseButton.setOnClickListener(this);
        mCloseButton.setOnLongClickListener(this);
        
    }
    
    @Override
	public void onItemClick(AdapterView parent, View v, int position, long id) {
        ApplicationInfo app = (ApplicationInfo) parent.getItemAtPosition(position);
		// set bound
		if (v != null) {
		    Rect targetRect = new Rect();
		    v.getGlobalVisibleRect(targetRect);
		    try{
		    	app.intent.setSourceBounds(targetRect);
		    }catch(NoSuchMethodError e){};
		}        
        mLauncher.startActivitySafely(app.intent);
        if (mLauncher.autoCloseFolder) {
            mLauncher.closeFolder(this);
        }
    }

    @Override
	public void onClick(View v) {
        mLauncher.closeFolder(this);
    }

    @Override
	public boolean onLongClick(View v) {
        mLauncher.closeFolder(this);
        return true;
    }

    @Override
	public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
        if (!view.isInTouchMode()) {
            return false;
        }
        mIsOnLongClick = true;
        ApplicationInfo app = (ApplicationInfo) parent.getItemAtPosition(position);
        if (mLauncher.isAllAppsVisible()) {             
            //mDragger.startDrag(view, this, app, DragController.DRAG_ACTION_MOVE);            
        } else {
            mDragger.startDrag(view, this, app, DragController.DRAG_ACTION_COPY);
            mLauncher.closeFolder(this);
            mDragItem = app;
        }

        return true;
    }

    public void setDragger(DragController dragger) {
        mDragger = dragger;
    }

    @Override
	public void onDropCompleted(View target, boolean success) {
    }

    /**
     * Sets the adapter used to populate the content area. The adapter must only
     * contains ApplicationInfo items.
     *
     * @param adapter The list of applications to display in the folder.
     */
    void setContentAdapter(BaseAdapter adapter) {
        mContent.setAdapter(adapter);
    }

    void notifyDataSetChanged() {
        ((BaseAdapter) mContent.getAdapter()).notifyDataSetChanged();
    }

    void setLauncher(Launcher launcher) {
        mLauncher = launcher;
    }
    
    /**
     * @return the FolderInfo object associated with this folder
     */
    FolderInfo getInfo() {
        return mInfo;
    }

    // When the folder opens, we need to refresh the GridView's selection by
    // forcing a layout
    void onOpen() {
        mContent.requestLayout();
    }

    void onClose() {
        final Workspace workspace = mLauncher.getWorkspace();
        if(mIsOnLongClick && !mLauncher.isAllAppsVisible()){
            workspace.getChildAt(workspace.getCurrentScreen())
            .setBackgroundDrawable(mLauncher.bitmap2drawable(R.drawable.addwidget_bg));
            mIsOnLongClick = false;
        }
        workspace.getChildAt(workspace.getCurrentScreen()).requestFocus();
    }

    void bind(FolderInfo info) {
        mInfo = info;
        mCloseButton.setText(info.title);
    }

    @Override
    public void onDragStart(View v, DragSource source, Object info,
            int dragAction) {
        // TODO Auto-generated method stub
        
    }

    @Override
    public void onDragEnd() {
        // TODO Auto-generated method stub
        
    }

}
