PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/lewa_ace.mk \
    $(LOCAL_DIR)/lewa_anzu.mk \
    $(LOCAL_DIR)/lewa_blade.mk \
    $(LOCAL_DIR)/lewa_bravo.mk \
    $(LOCAL_DIR)/lewa_bravoc.mk \
    $(LOCAL_DIR)/lewa_buzz.mk \
    $(LOCAL_DIR)/lewa_captivatemtd.mk \
    $(LOCAL_DIR)/lewa_click.mk \
    $(LOCAL_DIR)/lewa_coconut.mk \
    $(LOCAL_DIR)/lewa_cooper.mk \
    $(LOCAL_DIR)/lewa_crespo.mk \
    $(LOCAL_DIR)/lewa_crespo4g.mk \
    $(LOCAL_DIR)/lewa_desirec.mk \
    $(LOCAL_DIR)/lewa_dream_sapphire.mk \
    $(LOCAL_DIR)/lewa_droid2.mk \
    $(LOCAL_DIR)/lewa_droid2we.mk \
    $(LOCAL_DIR)/lewa_encore.mk \
    $(LOCAL_DIR)/lewa_epicmtd.mk \
    $(LOCAL_DIR)/lewa_espresso.mk \
    $(LOCAL_DIR)/lewa_es209ra.mk \
    $(LOCAL_DIR)/lewa_fascinatemtd.mk \
    $(LOCAL_DIR)/lewa_hallon.mk \
    $(LOCAL_DIR)/lewa_hero.mk \
    $(LOCAL_DIR)/lewa_heroc.mk \
    $(LOCAL_DIR)/lewa_inc.mk \
    $(LOCAL_DIR)/lewa_iyokan.mk \
    $(LOCAL_DIR)/lewa_jordan.mk \
    $(LOCAL_DIR)/lewa_galaxys2.mk \
    $(LOCAL_DIR)/lewa_galaxys2att.mk \
    $(LOCAL_DIR)/lewa_galaxysbmtd.mk \
    $(LOCAL_DIR)/lewa_galaxysmtd.mk \
    $(LOCAL_DIR)/lewa_generic.mk \
    $(LOCAL_DIR)/lewa_glacier.mk \
    $(LOCAL_DIR)/lewa_legend.mk \
    $(LOCAL_DIR)/lewa_leo.mk \
    $(LOCAL_DIR)/lewa_liberty.mk \
    $(LOCAL_DIR)/lewa_mango.mk \
    $(LOCAL_DIR)/lewa_mecha.mk \
    $(LOCAL_DIR)/lewa_mesmerizemtd.mk \
    $(LOCAL_DIR)/lewa_mimmi.mk \
    $(LOCAL_DIR)/lewa_morrison.mk \
    $(LOCAL_DIR)/lewa_motus.mk \
    $(LOCAL_DIR)/lewa_one.mk \
    $(LOCAL_DIR)/lewa_p970.mk \
    $(LOCAL_DIR)/lewa_p990.mk \
    $(LOCAL_DIR)/lewa_p999.mk \
    $(LOCAL_DIR)/lewa_passion.mk \
    $(LOCAL_DIR)/lewa_robyn.mk \
    $(LOCAL_DIR)/lewa_saga.mk \
    $(LOCAL_DIR)/lewa_satsuma.mk \
    $(LOCAL_DIR)/lewa_shadow.mk \
    $(LOCAL_DIR)/lewa_shakira.mk \
    $(LOCAL_DIR)/lewa_sholes.mk \
    $(LOCAL_DIR)/lewa_showcasemtd.mk \
    $(LOCAL_DIR)/lewa_smb_a1002.mk \
    $(LOCAL_DIR)/lewa_smb_a1004.mk \
    $(LOCAL_DIR)/lewa_smb_a1011.mk \
    $(LOCAL_DIR)/lewa_smb_b9701.mk \
    $(LOCAL_DIR)/lewa_smultron.mk \
    $(LOCAL_DIR)/lewa_speedy.mk \
    $(LOCAL_DIR)/lewa_supersonic.mk \
    $(LOCAL_DIR)/lewa_tass.mk \
    $(LOCAL_DIR)/lewa_u8150.mk \
    $(LOCAL_DIR)/lewa_u8220.mk \
    $(LOCAL_DIR)/lewa_urushi.mk \
    $(LOCAL_DIR)/lewa_v9.mk \
    $(LOCAL_DIR)/lewa_vega.mk \
    $(LOCAL_DIR)/lewa_vision.mk \
    $(LOCAL_DIR)/lewa_vivo.mk \
    $(LOCAL_DIR)/lewa_vivow.mk \
    $(LOCAL_DIR)/lewa_z71.mk \
    $(LOCAL_DIR)/lewa_zeppelin.mk \
    $(LOCAL_DIR)/lewa_zero.mk \
    $(LOCAL_DIR)/lewa_zeus.mk \
    $(LOCAL_DIR)/lewa_zeusc.mk \
    $(LOCAL_DIR)/lewa_u8500.mk \
    $(LOCAL_DIR)/lewa_c8650.mk \
    $(LOCAL_DIR)/lewa_u8800.mk \
    $(LOCAL_DIR)/lewa_u8800pro.mk \
    $(LOCAL_DIR)/lewa_u880.mk  \
    $(LOCAL_DIR)/lewa_u8800x.mk \
    $(LOCAL_DIR)/lewa_roamer.mk \
    $(LOCAL_DIR)/lewa_c8500.mk \
    $(LOCAL_DIR)/lewa_olympus.mk \
    $(LOCAL_DIR)/lewa_marvel.mk \
    $(LOCAL_DIR)/lewa_n880s.mk \
    $(LOCAL_DIR)/lewa_n880.mk \
    $(LOCAL_DIR)/lewa_mione_plus.mk
